### ISSUE TITLE
Collaborate 'more information' links broken

### ISSUE THREAD

**Issue by BillMills** [mozillascience/site#23] opened 2015-03-12 02:23 UTC
It appears that some database references got flipped when submitting projects - the text of the anchor tag and the href attribute are getting swapped after submitting a project to the database and reloading the submission, breaking the 'More Information' links on all new projects.

**Comment by acabunoc** [comment] 2015-03-31 14:16
duplicate of #21 - closing

**Closed by acabunoc** 2015-03-31 14:16 UTC
Labels: bug
